name = "SlimPlotting"
uuid = "f6d04670-764e-495b-a720-91c3c9a588ff"
authors = ["Mathias Louboutin <mathias.louboutin@gmail.com>"]
version = "1.0.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ColorSchemes = "3"
Requires = "1.3.0"
PythonPlot = "1"
PyPlot = "2"
julia = "1"

[extensions]
PyPlotSlimExt = "PyPlot"
PythonPlotSlimExt = "PythonPlot"

[weakdeps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
